text = 'съешь еще этих мягких французских булок'
print(text[0])
print(text[1])
print(text[len(text)-1])
print(text[-5])
print(text[:])
print(text[:2])
print(text[len(text)-2:])
print(text[2:9])
print(text[6:-18])
print(text[0:len(text):6])
